django/src/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    #url(r'^admin/defender/', include('defender.urls')),

    url(r'^roles/', include('roles.urls')),
    url(r'^targets/', include('targets.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html', content_type='text/html'), name="index"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

django/src/roles/urls.py
from .views import RolesListView, RolesDetailView
from django.conf.urls import url

urlpatterns = (
    url(r'^list/$', RolesListView.as_view()),
    url(r'^detail/(?P<pk>\d+)/$', RolesDetailView.as_view()),
)

django/src/targets/urls.py
from .views import TargetsListView, TargetsDetailView
from django.conf.urls import url

urlpatterns = (
    url(r'^list/$', TargetsListView.as_view()),
    url(r'^detail/(?P<pk>\d+)/$', TargetsDetailView.as_view()),
)

django/src/tasks/urls.py
from .views import TasksListView, TasksDetailView
from django.conf.urls import url

urlpatterns = (
    url(r'^list/$', TasksListView.as_view()),
    url(r'^detail/(?P<pk>\d+)/$', TasksDetailView.as_view()),
)

django/src/roles/models.py
from django.db import models
from model_utils.models import TimeStampedModel

class Role(TimeStampedModel):
    title  = models.CharField(
        max_length      = 128,
        blank           = False,
        null            = False,
        verbose_name    = "Название"
    )

    class Meta():
        verbose_name        = "Роль"
        verbose_name_plural = "Роли"

    def __str__(self):
        return self.title

django/src/targets/models.py
from django.db import models
from roles.models import Role
from model_utils.models import TimeStampedModel

class Target(TimeStampedModel):
    TARGET_TYPES = [
        (1, "Проект"),
        (2, "Навык"),
    ]
    target_type = models.PositiveIntegerField(
        verbose_name="Тип цели",
        choices=TARGET_TYPES,
        default=1,
        blank=False,
        null=False,
    )
    parent = models.ForeignKey(
        to              = "self",
        null            = True,
        blank           = True,
        verbose_name    = "Глобальная цель",
        on_delete       = models.CASCADE,
    )
    role = models.ForeignKey(
        to              = Role,
        blank           = False,
        null            = False,
        verbose_name    = "Роль",
        on_delete       = models.CASCADE,
    )
    title  = models.CharField(
        max_length      = 128,
        blank           = False,
        null            = False,
        verbose_name    = "Цель"
    )
    description = models.TextField(
        blank           = False,
        null            = False,
        verbose_name    = "Описание"
    )

    class Meta():
        verbose_name        = "Цель"
        verbose_name_plural = "Цели"

    def __str__(self):
        return self.title

django/src/tasks/models.py
from django.db import models
from targets.models import Target
from model_utils.models import TimeStampedModel
from model_utils import Choices
from model_utils.fields import MonitorField, StatusField
from tinymce.models import HTMLField

class Task(TimeStampedModel):
    STATUS = Choices('Новая', 'В работе', 'Готово')
    status = StatusField()
    status_working_at = MonitorField(monitor='status', when=['В работе'])
    status_complete_at = MonitorField(monitor='status', when=['Готово'])

    parent = models.ForeignKey(
        to              = 'self',
        blank           = True,
        null            = True,
        verbose_name    = "Родительская задача",
        on_delete       = models.CASCADE,
        related_name    = '+',
    )
    target = models.ForeignKey(
        to              = Target,
        blank           = False,
        null            = False,
        verbose_name    = "Цель",
        on_delete       = models.CASCADE
    )
    title  = models.CharField(
        max_length      = 128,
        blank           = False,
        null            = False,
        verbose_name    = "Задача"
    )
    description = HTMLField(
        blank           = False,
        null            = False,
        verbose_name    = "Описание"
    )
    is_blocked  = models.ForeignKey(
        to              = 'self',
        blank           = True,
        null            = True,
        verbose_name    = "Блокируется",
        on_delete       = models.CASCADE,
        related_name    = '+',
    )

    class Meta():
        verbose_name        = "Задача"
        verbose_name_plural = "Задачи"

    def __str__(self):
        return self.title

django/src/roles/views.py
import logging
from django.views.generic import ListView, DetailView
from .models import Role

logger = logging.getLogger('default')

class RolesDetailView(DetailView):
    model = Role

    def get_object(self, queryset=None):
        object = super(RolesDetailView, self).get_object()
        return object

class RolesListView(ListView):
    model = Role

django/src/targets/views.py
import logging
from django.views.generic import ListView, DetailView
from .models import Target

logger = logging.getLogger('default')

class TargetsDetailView(DetailView):
    model = Target

    def get_object(self, queryset=None):
        object = super(TargetsDetailView, self).get_object()
        return object

class TargetsListView(ListView):
    model = Target
    template_name = "targets/target_list.html"

    """
    #Изменяет список задач, рекурсивно вкладывая дочерние внутрь родительских
    def get_queryset(self):
        def form_subtargets(root_targets):
            for root_target in root_targets:
                subtargets = list(Target.objects.filter(parent=root_target))
                if len(subtargets) > 0:
                    print(type(subtargets))
                    root_target.subtargets = form_subtargets(subtargets)
            return root_targets

        root_targets = list(Target.objects.filter(parent=None))
        print(root_targets)
        root_targets = form_subtargets(root_targets)
        print(root_targets)
        print(root_targets[0].subtargets)
        return root_targets
    """

django/src/tasks/views.py
import logging
from django.views.generic import ListView, DetailView
from .models import Task

logger = logging.getLogger('default')

class TasksDetailView(DetailView):
    model = Task

    def get_object(self, queryset=None):
        object = super(TasksDetailView, self).get_object()
        return object

class TasksListView(ListView):
    model = Task

django/src/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org</title>
    <link rel="stylesheet" href="style.css"/>
</head>
<body>
    <div class="roles_level">
        <div v-for="role in roles" class="role">
          {{ role.text }}
        </div>
    </div>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
</body>
</html>

django/src/templates/home.html
{% load cms_tags sekizai_tags menu_tags %}
<html>
    <head>
        <title>{% page_attribute "page_title" %}</title>
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% show_menu %}
        {% show_breadcrumb %}
        {% placeholder "content" %}
        {% render_block "js" %}
    </body>
</html>

django/src/templates/roles/role_list.html
{% extends "root.html" %}
{% block content %}
<table id="roles" class="table table-striped table-bordered">
  <thead>
    <tr>
      <td>Название</td>
    </tr>
  </thead>
  <tbody>
  {% for role in object_list %}
    <tr>
      <td><a href="/targets/list/?from={{role.title}}">{{role.title}}</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

django/src/templates/root.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
    <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  </head>
  <body>
    <nav>
      <a href="/roles/list/" title="Открыть список ролей">Роли</a> 
      -> <a href="/targets/list/" title="Открыть список целей">Цели</a> -> 
      <a href="/tasks/list/" title="Открыть список задач">Задачи</a>
    </nav>
    {% block content %}{% endblock %}

  <script>
    function getAllUrlParams(url) {
      /* @author Yaphi Berhanu */
      var queryString = url ? url.split('?')[1] : window.location.search.slice(1);
      var obj = {};
      if (queryString) {
        queryString = queryString.split('#')[0];
        var arr = queryString.split('&');
        for (var i=0; i<arr.length; i++) {
          var a = arr[i].split('=');
          var paramNum = undefined;
          var paramName = a[0].replace(/\[\d*\]/, function(v) {
            paramNum = v.slice(1,-1);
            return '';
          });
          var paramValue = typeof(a[1])==='undefined' ? true : a[1];
          paramName = paramName.toLowerCase();
          paramValue = paramValue.toLowerCase();
          if (obj[paramName]) {
            if (typeof obj[paramName] === 'string') {
              obj[paramName] = [obj[paramName]];
            }
            if (typeof paramNum === 'undefined') {
              obj[paramName].push(paramValue);
            }
            else {
              obj[paramName][paramNum] = paramValue;
            }
          }
          else {
            obj[paramName] = paramValue;
          }
        }
      }
      return obj;
    }
    var table;
    $(document).ready(function(){
      table = $('#targets').DataTable();
      if(getAllUrlParams().from){
          table.search(decodeURIComponent(getAllUrlParams().from)).draw();
      }
      
    });

  </script>
  </body>
</html>

django/src/templates/targets/target_list.html
{% extends "root.html" %}
{% block content %}
<table id="targets" class="table table-striped table-bordered">
  <thead>
    <tr>
      <td>Название</td>
      <td>Тип</td>
      <td>Родитель</td>
      <td>Роль</td>
      <td>Описание</td>
    </tr>
  </thead>
  <tbody>
  {% for target in object_list %}
    <tr>
      <td><a href="/tasks/list/?from={{target.title}}">{{target.title}}</a></td>
      <td>{{target.get_target_type_display}}</td>
      <td>{{target.parent}}</td>
      <td>{{target.role}}</td>
      <td>{{target.description}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

django/src/templates/tasks/task_list.html
{% extends "root.html" %}
{% block content %}
<table id="tasks" class="table table-striped table-bordered">
  <thead>
    <tr>
      <td>Название</td>
      <td>Родитель</td>
      <td>Цель</td>
      <td>Описание</td>
      <td>Статус</td>
    </tr>
  </thead>
  <tbody>
  {% for task in object_list %}
    <tr>
      <td>{{task.title}}</td>
      <td>{% if task.parent %}{{task.parent}}{%else%}-{%endif%}</td>
      <td>{{task.target}}</td>
      <td>{{task.description|safe}}</td>
      <td>{{task.status}}</td>

    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}